name: publish site
on: # when to launch workflow
  push: # 在从本地main分支被push到GitHub仓库时push local main branch to Github repo
    branches:
      - main
  pull_request: # merge PR on main branch
    branches:
      - main
jobs: # content of workflow
  deploy:
    runs-on: ubuntu-latest # create a cloud virtual machine
    steps:
      - uses: actions/checkout@v2 # checkout to main branch
      - uses: actions/setup-python@v2 # install python3 env
        with:
          python-version: 3.x
      - run: pip install -r requirements.txt # use pip to install
      - run: mkdocs gh-deploy --force # deploy gh-pages
